### ISSUE TITLE
Database Error -Unable to install Neos using Nginx

### ISSUE THREAD

**Issue by christophengelmayer** [webdevops/Neos-docker-boilerplate#1]
I ran into a database error while trying to install Neos.
### To reproduce the issue:
1. Setup Neos-docker-boilerplate and install Neos
   
   ```
   git clone https://github.com/webdevops/Neos-docker-boilerplate
   cd Neos-docker-boilerplate
   cp docker-compose.development.yml docker-compose.yml
   make create neos
   make up
   ```
2. Open http://neos.docker/setup in your browser
3. Enter the Setup Password (found in `app/Data/SetupPassword.txt`)
4. In the next step, the following Error occurs:
   
   > Database Error
   > Sorry, we detected an error with your database. Check your log files in Data/Logs/\* for more information.
   > # 0: An error occurred in the Database Abstraction Layer.
   > 
   > You might want to configure or check your database configuration in the setup.
   
   The logfile says
   
   ```
   16-07-20 10:04:05 482        CRITICAL  DBAL                 Exception in line 133 of  /app/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused - See also: 2016072010035775a5b3.txt
   previousException => Exception #2002 in line 41 of /app/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:  SQLSTATE[HY000] [2002] Connection refused
   
   16-07-20 10:04:05 482        CRITICAL  Flow                 Exception in line 56 of /opt/tmp/Development/Cache/Code/Flow_Object_Classes/TYPO3_Flow_Persistence_Doctrine_QueryResult.php: An error occurred in the Database Abstraction Layer. - See also: 20160720100357e00d9e.txt
   ```
### Fix:

**I was able to fix the problem using the Apache instead of Nginx box in `Dockerfile.development`** 

```
FROM webdevops/php-apache-dev:ubuntu-16.04
```

**Comment by mblaschke** [comment]
nginx also with ubuntu-16.04 or a different tag?

Maybe the database was still trying to setup the database files so it wasn't fully up. Can you please retry it with the nginx image?

**Comment by christophengelmayer** [comment]
The described error occurs using the default `php-nginx-dev:ubuntu-16.04`.

I'm using [Docker for Mac](https://docs.docker.com/engine/installation/mac/) beta and the standalone version of [Dinghy HTTP Proxy](https://github.com/codekitchen/dinghy-http-proxy). Maybe the issue is related to this setup. On the other hand, it works with apache, so it should work with Nginx too, i guess.

**However, if someone is running into the same problem, a quick fix is to switch to Apache.**

**Comment by christophengelmayer** [comment]
Works now.

Thanks for the fast fix and this awesome project!
